project:
  type: website

website:
  title: "Analyse Rumigest Duo"
  navbar:
    left:
      - text: "Analyse"
        href: index.html
      - text: "Dashboard"
        href: https://dashboard.costeranalytics.nl/analyse_rumigestduo/