project:
  type: website
  output-dir: ../docs
  
execute:
  freeze: true

website:
  title: "Analyse Rumigest Duo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analyseapp.qmd
        text: Interactive App

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
    

  
lang: nl