project:
  type: website
  output-dir: ../docs

website:
  title: "Analyse Rumigest Duo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analyseapp.qmd
        text: Interactive App

format:
  html:
    theme: cosmo
    toc: true